### ISSUE TITLE
Add support for ClassicalXOR gate

### ISSUE THREAD

**Issue by amicciche** [QuantumSavory/Quantikz.jl#15]
The ClassicalXOR gate defined in my recent pull request on QuantumClifford.jl would benefit from being able to be displayed in the Quantikz rendered circuit image.

**Comment by Krastanov** [comment]
done in 88a6f991b2e843c83853f3b573ff2ba992f54162

![image](https://github.com/QuantumSavory/Quantikz.jl/assets/705248/ccb22d6d-bd07-4f51-8e84-89c7c5297dfa)
